# Schema for the configuration files of the Social Profile Privacy module.

social_profile_privacy.settings:
  type: config_object
  label: 'Social Profile Privacy settings'
  mapping:
    user_form_display:
      type: string
      label: 'Privacy settings on display of user form'
    user_form_display_field_groups:
      type: sequence
      label: 'Field groups of user form'
      sequence:
        type: string
        label: 'Field group'
    profile_form_display:
      type: string
      label: 'Privacy settings on display of profile form'
    profile_form_display_field_groups:
      type: sequence
      label: 'Field groups of profile form'
      sequence:
        type: string
        label: 'Field group'
    limit_search_and_mention:
      type: boolean
      label: 'Limit search and mention'
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: integer
        label: 'State'
    disclaimer:
      type: mapping
      label: 'Disclaimer'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Format'
