name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install dependencies
        run: >
        composer self-update --1
        composer update

      - name: Run phpcs with Drupal coding standards.
        run: >
          ./vendor/bin/phpcs \
            --report-full \
            --standard="Drupal" -n \
            --extensions="php,module,inc,install,test,profile,theme" \
            ./ \
            --ignore=*/node_modules/* \
            --ignore=*.css \
            --ignore=social.info.yml \
            --ignore=.github/PULL_REQUEST_TEMPLATE.md
